### ISSUE TITLE
Error when run the server of plus-quic-go

### ISSUE THREAD

**Issue by vanvantong** [mami-project/plus-quic-go#2]
Hi the administrator of plus-quic-go,

I try to implement the plus-quic-go. I follow the instruction from your github and built successfully.
I run the server by this command:

_go run example/main.go -www /var/www/_

When I run the client side with:

_chromium-browser --allow-file-access-from-files --user-data-dir=/tmp/chrome-profile --no-proxy-server --enable-quic --origin-to-force-quic-on=quic.clemente.io:443 --host-resolver-rules='MAP quic.clemente.io:443 127.0.0.1:6121' https://quic.clemente.io_

I got some errors in the server side. Server terminated:

_servePLUS
The wizard is not happy with the magic._

I also attached my screenshot of wireshark.
![wireshark](https://user-images.githubusercontent.com/9009495/34450633-c678f518-ed40-11e7-8e88-ac4e73af4b31.png)
Any body know how to solve this error?
Is there any tool for capturing the plus packet?

Thank you in advance!
Happy new year!

**Comment by FMNSSun** [comment]
This means the magic didn't match the magic value as specified by the PLUS draft. This means that one side isn't speaking PLUS which in your case would be chromium because chromium doesn't speak PLUS. 

The magic is the first 28 bits of a PLUS packet (the first 4 bytes, minus the 4 bits for the LRSX flags). 

You can use the client program (should also be in the example directory)  (as mentioned in https://github.com/mami-project/plus-quic-go/tree/master/example/client). 

As mentioned: There's currently absolutely no software out there in the wild that speaks PLUS and we only have a few very small example programs (such as the server and a website crawler (that's the client)) that use PLUS.

**Comment by FMNSSun** [comment]
And wireshark can't disect PLUS packets btw. If you want to capture and inspect plus packets you can use our fork of go-packet (https://github.com/FMNSSun/gopacket) and plus-pcap (https://github.com/FMNSSun/plus-pcap) because wireshark doesn't understand PLUS.

**Comment by vanvantong** [comment]
Thank you very much for your responding!

**Comment by FMNSSun** [comment]
Alright, then I'll consider this closed.
